# 默认配置
[default]
# ----- 开发设置 -----
DEBUG = '@bool False'

# ----- 基本设置 -----
# 云API密钥
SESSION_TOKEN = '@none None'
# 默认地域
DEFAULT_REGION = '@none None'

# ----- COS对象存储 -----
# COS默认地域，默认使用DEFAULT_REGION
COS_DEFAULT_REGION = '@none None'
COS_DEFAULT_PREFIX = ''

# ----- SCF云函数 -----
# SCF运行环境
SCF_RUNTIME = '@none None'
# SCF默认命名空间，默认为default
SCF_DEFAULT_NAMESPACE = 'default'
# SCF默认函数名称
SCF_DEFAULT_FUNCTION_NAME = '@none None'

# ----- EB事件总线 -----
# EB默认地域，默认使用DEFAULT_REGION
EB_DEFAULT_REGION = '@none None'
# EB支持地域
EB_SUPPORTED_REGIONS = ['ap-beijing', 'ap-chengdu', 'ap-chongqing', 'ap-guangzhou', 'ap-hongkong',
    'ap-shanghai', 'ap-singapore', 'eu-moscow', 'na-siliconvalley']
# EB支持地域的文档
EB_SUPPORTED_REGIONS_DOC = 'https://cloud.tencent.com/document/product/1359/67707#.E5.9C.B0.E5.9F.9F.E5.88.97.E8.A1.A8'

# ----- SMS短信服务 -----
# SMS支持地域
SMS_SUPPORTED_REGIONS = ['ap-beijing', 'ap-guangzhou', 'ap-nanjing']
# SMS支持地域的文档
SMS_SUPPORTED_REGIONS_DOC = 'https://cloud.tencent.com/document/api/382/52071#.E5.9C.B0.E5.9F.9F.E5.88.97.E8.A1.A8'
